### ISSUE TITLE
Unable to assign device in Earnapp

### ISSUE THREAD

**Issue by AnotherRandomNameNotTaken** [XternA/income-generator#10]
This is probably more of an issue with Earnapp.
There is no way to register a device in the Earnapp dashboard.
Reading through the documentation on Linux installation on Earnapp, an HTML link is now given in the installation process which links the device. 
[https://help.earnapp.com/hc/en-us/articles/10261224561553-Installation-instructions-and-hardware-software-requirements](https://help.earnapp.com/hc/en-us/articles/10261224561553-Installation-instructions-and-hardware-software-requirements)

**Comment by XternA** [comment]
Seems like they've removed the ability to manually add via the dashboard.

There used to be two ways to register the device. 

1. Given you've generated the ID from the tool it will give you an ID like `sdk-node-90asnqw0asfnas0as241124` for example. You take this ID and register it in your EarnApp dashboard, by adding a new device. You can also view the UUID again in the config file via the tool.
2. The other approach is you use `https://earnapp.com/r/` and append your ID at the end of the URL `sdk-node-0d1b2d41edf349d2a005bcd9b1ac7fc1` to register the device. So your URL looks like this: `https://earnapp.com/r/sdk-node-0d1b2d41edf349d2a005bcd9b1ac7fc1`

I'll modify the tool so that it will generate the dynamic link with the UUID attached.

**Comment by XternA** [comment]
Changes have been updated to reflect this.

Please proceed to update the tool, and get the latest changes. No need to reset any config.

```markdown
Income Generator Application Manager
----------------------------------------
.
.
.
8. Change Resource Limits
9. Update/Reset Config
0. Quit

Select an option (1-9):
```

```markdown
Income Generator Application Manager
----------------------------------------

1. Reset resource limit only
2. Reset all back to default
3. Check and get update
0. Return to Main Menu

Select an option (1-3):
```

Then run through the setup again, configure only for EarnApp, register with the link, and then just `press enter` to skip through the rest of the config.

You will now see a new description with a registration link once you've generated a new UUID.
```markdown
Configuring application 1 of 16

[ EARNAPP ]
Do you want to auto-generate a new UUID for EARNAPP_DEVICE_UUID? (y/n): y
A new UUID has been auto-generated for EARNAPP_DEVICE_UUID: sdk-node-1270aecf4bccb53a98c7c29b1d0d7f2e
Register the new device with the following link: https://earnapp.com/r/sdk-node-1270aecf4bccb53a98c7c29b1d0d7f2e

Press Enter to continue...
```

**Comment by XternA** [comment]
Marking this as resolved.
