### ISSUE TITLE
long curl command not working

### ISSUE THREAD

**Issue by lalejand** [XternA/income-generator#30]
When I perform `curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat`, I get that error:

```
Invoke-WebRequest : Impossible de trouver un paramètre positionnel acceptant l'argument « --ssl-no-revoke ».
Au caractère Ligne:1 : 1
+ curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by XternA** [comment]
Hi, could you kindly run this in `cmd.exe` or in the new Windows Terminal (cmd.exe) please and not via `Powershell`.

Also please translate the error to English please as I it's easier than for me to guess what language it is.

**Comment by lalejand** [comment]
Looks like it worked in cmd.exe.

```
C:\Users\onurb>curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1164  100  1164    0     0   4789      0 --:--:-- --:--:-- --:--:--  4829

C:\Users\onurb>for /f "delims=" %i in ('powershell -Command "[Environment]::GetEnvironmentVariable('Path', 'User')"') do set USERPATH=%i && setx PATH %USERPATH%;%APPDATA%\IGM

C:\Users\onurb>set USERPATH=C:\Users\onurb\AppData\Local\Microsoft\WindowsApps;   && setx PATH %USERPATH%;C:\Users\onurb\AppData\Roaming\IGM

RÉUSSITE : la valeur spécifiée a été enregistrée.
```

It says success at the end.

But, then if I run `igm `in cmd.exe I get that:
```
C:\Users\onurb>igm
'igm' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

Which means "igm' is not recognized as an internal or external command or external command, an executable program or a command file."

If I run `igm `in the powershell, I get that:

```
PS C:\Users\onurb> igm
No winget found on the system. Please install winget before proceeding.
```

I'm on windows 11.

**Comment by XternA** [comment]
Thanks for the detailed explanation.

To keep it short, you've not done anything wrong and the procedure is correct.

1. Why you "igm" is not recognised is because after the alias has been registered, you have to restart the command line so that it can recognise the alias. Just like in Linux you have you have to source the changes. Which is why you see it in `Powershell` because you opened a new session. If you open a new `cmd` or any other command shell, it's recognised.

2. `Winget` is installed by default on Windows 11. This is the default package manage for Windows now, like `apt-get` in Linux.

This means you're partially set. I think the only thing you're missing now as part of the pre-requisite is `WSL` Windows Subsystem for Linux.

Please follow this guide to install WSL and enable it: https://github.com/XternA/income-generator/wiki/Windows-Guide.

After that close all your Command line. Then load a new one and try `igm` again. It should load after that. If it does then you can proceed as normal and install the container runtime from the tool. This would be docker. The rest of the boilerplate should be taken care of thereafter.

**Comment by lalejand** [comment]
I closed both cmd and powershell,and  even restarted the computer.
But now if I write `igm` in cmd or powershell, I get the same error message:

```
C:\Users\onurb>igm
No winget found on the system. Please install winget before proceeding.
```

```
PS C:\Users\onurb> igm
No winget found on the system. Please install winget before proceeding.
```

(WSL is installed)

**Comment by XternA** [comment]
@lalejand I think I know what the problem is. Since you're using your Windows in another language, the command to check for the prerequite is technically in English. Therefore, despite WSL is actually installed the command is basically invalid.

I've updated the bootstrap script using another approach to check. If I'm correct, it should work this time.

Please kindly run the following command to update your bootstrap script with the latest:
```markdown
curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat
```

You won't need to re-register the alias anymore.

Appreciate your patience and apologies for the delayed response.

**Comment by lalejand** [comment]
Hi, thx. But still not working :/

![image](https://github.com/user-attachments/assets/afa9ac58-3fd8-4e13-88c8-62c1397d1c24)

**Comment by lalejand** [comment]
I had to perform what is explained in point number 5 in that page https://thewindowsclub.blog/fr/how-to-fix-winget-is-not-recognized-on-windows/ in order to be able to get winget work

**Comment by XternA** [comment]
Ahh got it. It was missing the path for `winget`, hence it couldn't locate the binary executable despite it's actually been installed.

Strange how your environmental path was messed up. Just based on the usual generic error, it's usually when the tool isn't installed. But I guess not being able to read your language made it more vague.

Thanks for the info, this will be helpful for others in the future.
