### ISSUE TITLE
Suggestion : add Packetshare

### ISSUE THREAD

**Issue by lalejand** [XternA/income-generator#35]
Why didn't you propose Packetshare integration? https://www.packetshare.io/index.html

**Comment by XternA** [comment]
There was no container binary released at the time when I first discovered it. Seems like they've only added it more recently. In fact there are a couple more applications around that I'm waiting on the support for container versions before I can add it to the IGM stack.

I do appreciate you mentioning this back to me know as I've just checked they've done a lot of development work since. I will add this to the tool. Stay updated in the next few days as I add it to the backlog and push out a new update with this integration.

Thanks again for letting me know to re-visit this again.

**Comment by XternA** [comment]
This is now added to the stack.
