### ISSUE TITLE
Application setup issue when trying to add settings for new application

### ISSUE THREAD

**Issue by d-taborda** [XternA/income-generator#42]
Hello,

Recently, I have been having issues using the "Setup Configuration" menu to configure new apps.
If i go to the menu **2. Setup Configuration> 1. Set up configuration** and input "Y" to start the application setup process, it does not work.
In the past, when I enable a new application then use this menu, it will open the wizard to configure the settings required for that application, nowards, it just does this: 
![image](https://github.com/user-attachments/assets/454e5326-a8cb-4b05-8465-ea8bfb4906c4)

Then I can only press Enter and it will exit.

Do you know how to resolve this issue without breaking the existing config (that works well for now for the other configured apps I have)? 
I believe I can also just edit the config file manually but not knowing the exact parameters required for the application makes it more prone to errors, this method was much easier to perform the setup.

Thank you.

**Comment by XternA** [comment]
Hi, thanks for the detailed explanation.

If you've been following the update instructions, technically you shouldn't face any issues. However I think some system files are messed up or clashed since updates.

The easiest solution whilst keeping minimal disruptions, do the following:

1. You should be able to view the credentials file from the tool. Do that, and copy out all the credential data only as is (omit everything else that isn't). Put it in a notepad temporarily.
2. Stop and remove all applications, `option 5` on main menu.
3. Reset the tool completely, and force check and update the tool so you're in sync with the latest.
4. Now `Setup Configuration` > `Edit config file` and paste back the credentials as is into the tool. Ensure that the last line is an empty new line only, no more than that. Save the file.
5. Now on that same menu, option 4 to enable or disable your applications again if you have any previously.
6. Re-apply your desired resource limit if you previously have set.
7. Install, it should install back all the applications that you have previously configured.

There is going to be upcoming release soon and proxy feature support so I want to ensure that your configurations now will be as up to date as possible to ensure there's no future disruptions. Due to the new features there are some internal changes that has been changed around so hope you understand why  the reason behind the following instructions.

Appreciate your patient and continued support once again.

**Comment by d-taborda** [comment]
Hello,

Thanks for the procedure.
After trying a few times I have completely deleted the tool and reinstalled it + reconfigured it by pasting the credential in the config file again. It is up to date, apps reinstalled and running.
However, the same issue remains. I can't see the wizard to configure new apps like Packetshare.
Worse case.. can you share the config file parameters/values that I am supposed to input? Otherwise, I am not sure how to resolve this.. But moving forward it will be difficult to configure new apps.

Thanks.

**Comment by XternA** [comment]
Hi, that's very strange. I have setup and configured the tool on a new host machine recently and it's working for me, even manually enabling just `Packetshare` alone and configuring the setup credentials is working as well.

If you've fully reset the tool, it should clean up everything in the tool folder.

Anyways, there's a new update, please update to this version and see if the issue still persists. Refer to the release notes for instructions before updating to version [1.11](https://github.com/XternA/income-generator/releases/tag/1.11).

If absolute worst case scenario, inspect your credentials file first, it should only be key-pair bindings and nothing else, e.g.
```dotenv
APP_USER=abc@example.com
APP_PASS=testPasswd
APP_UUID=123-abc-456-def
```

Finally, if all else fails use the following command to remove the tool completely:

### Windows

```bash
# Remove tool folder
wsl rm -rf ~/.income-generator ~/.igm

# De-register alias
wsl -e sh -c "sed -i '/alias igm=/d' $HOME/.aliases; sed -i '/alias igm=/d' $HOME/.${SHELL##*/}rc"

# Get bootstrap script again
curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat
```

### Linux & macOS
```bash
# Remove tool folder
rm -rf ~/.income-generator ~/.igm

# De-register alias
# Linux
sed -i '/alias igm=/d' $HOME/.aliases; sed -i '/alias igm=/d' "$HOME/.${SHELL##*/}rc"
# macOS
sed -i '' '/alias igm=/d' "$HOME/.aliases"; sed -i '' '/alias igm=/d' "$HOME/.${SHELL##*/}rc"

# Get the tool and register alias again
git clone --depth=1 https://github.com/XternA/income-generator.git ~/.igm
echo "alias igm=\"sh -c 'cd ~/.igm; sh start.sh \\\"\\\$@\\\"' --\"" >> ~/."${SHELL##*/}rc"; source ~/."${SHELL##*/}rc"
```

Now run IGM `igm` again and paste back in credentials. If it causes issue, scrap the credentials completely and go through the setup again. When asked for credential details and UUID etc, re-use entries from the backup credentials.

I know it's frustrating for your but hope this helps, and thanks for your patience.

The parameters for `Packetshare` is:

```dotenv
PACKETSHARE_EMAIL=<your_email>
PACKETSHARE_PASSWORD=<your_password>
```
