### ISSUE TITLE
Problems with docker on a 32 bits linux computer

### ISSUE THREAD

**Issue by lalejand** [XternA/income-generator#44]
I am trying to use igm on a 32 bits linux computer (OS: antiX).
I had to install Docker from outside igm performing "sudo apt install docker.io". Within igm, it was not working.
I igm, when I try to install the apps, I get an error that says: "unknown flag: --env-file".

**Comment by XternA** [comment]
I'm not too familiar with this particular Linux distro.

Judging from the command, it seems like a Debian based distro. I think the reason it's not working is from the package name, as it specifically uses `docker.io` instead of `docker-ce` that Debian/Ubuntu uses.

Strange, `--env-file` argument is related to Docker Compose command. Depending on the distro package version instead of using the new `docker compose`, it's possible it's using the older `docker-compose` Compose command. All `dotenv` files are loaded correctly for use when invoking Docker compose.

There's a good chance it might be using a very old version of Docker Compose. Try using the latest update of the tool. There's been quite a bit of refinement to cater for these issues.

**Comment by lalejand** [comment]
I updated the tool.
Now I get that error :
> Installing selective applications...
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22project%3Dproxy%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
start.sh: 248: docker-compose: not found
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/prune": dial unix /var/run/docker.sock: connect: permission denied
start.sh: 252: docker-compose: not found

**Comment by XternA** [comment]
Docker user group isn't set, hence Docker has no access to the `docker.sock`. 

Run `newgrp docker` and try again.

**Comment by lalejand** [comment]
When performing `newgrp docker` the system was asking a password I don't know.
I followed instructions here: https://docs.docker.com/engine/install/linux-postinstall/ (sudo groupadd... sudo usermod...) and then I was able to do `newgrp docker` without being asked a password.
But now the error in igm is:
```
Installing selective applications...
start.sh: 248: docker-compose: not found
Total reclaimed space: 0B
start.sh: 252: docker-compose: not found
Press Enter to continue...
```

**Comment by XternA** [comment]
Because you've installed docker manually, the docker package for your distro doesn't automatically install `Docker Compose` with it, hence, you will need to install `Docker Compose` separately.

I think your distro doesn't come with `Docker` and `Docker Compose` as standard. To use the native version of `Docker Compose` that's not compiled with Python and Uses from Docker directly you might need to re-install `Docker` with the following source.

```bash
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
```
Finally check if it exists:

```bash
docker compose version
```
