### ISSUE TITLE
NodePay issue but can't fix

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#60]
I tried those method in this https://github.com/XternA/income-generator/issues/49#issuecomment-2455993435 and this reinstall Nodepay, still not work at all
![Capture (3)](https://github.com/user-attachments/assets/abeee749-81b2-4fd8-9697-adae3e59340f)

**Comment by XternA** [comment]
Can you describe your environment so I can get a better picture of your hardware spec?

Sometimes it could be due to not enough resource as apps like these runs a chrome browser internally.

**Comment by thienha1** [comment]
My environment? U mean my spec? Here: 
![Capture (1)](https://github.com/user-attachments/assets/21b7dbe4-90aa-437e-8a52-9ca99ba01327)

**Comment by XternA** [comment]
OK Windows machine, and you should have more than enough resource.

To confirm, the WSL Linux distro is `Ubuntu`.

Since you're on Windows and the are most definitely using WSL, there shouldn't be any issue. Mostly it's usually due to the docker image of the app that will give you errors. The underlying container runs a headless browser with the Nodepay chrome extension to do the work.

There's one thing you need to be aware, The cookie token you obtain only persists for a week so you need to re-apply a new one and re-deploy the application again in order for the application to work. See if re-deploying after changing the cookie helps. Check this doc for that if you aren't aware already: https://github.com/XternA/income-generator/wiki/NodePay
