### ISSUE TITLE
EarnApp register device

### ISSUE THREAD

**Issue by thienha1** [XternA/income-generator#62]
I created UUID EarnApp like this
![Capture (5)](https://github.com/user-attachments/assets/3526da45-504a-4b0d-9f6d-8c4770a19d83)
but when apply to website after install and deploy then this happen!!
![ImportedPhoto_1733149556353](https://github.com/user-attachments/assets/fd7dee0a-d196-4134-8100-e593fd5e1f60)
I still dunno how to add this into EarnApp devices...

**Comment by XternA** [comment]
Use `igm view` to view and check all the app's credentials that you have setup. Find the part for `EarnApp` and see if the ID is the same as the one from your screenshot. If it isn't then it has changed. 

What you can do is run the credential setup, set a new UUID again. Then check the UUID from `igm view` and then install the app. It will use the UUID that is currently stored in your credential file. After the app has been installed, you can use the following link with the appended UUID and it will register.

`https://earnapp.com/r/<your_UUID_from_credential_file>`

Give that a go.

**Comment by XternA** [comment]
If it's causing the issue, check it see there isn't any `EarnApp` already deployed. If there is then simply remove traces and start again.

You can using `igm remove earnapp` to remove the application or `igm remove` to remove every single app and start again.

Confirm your EarnApp ID isn't already registered from the dashboard, if there is one then you can re-use it. Otherwise remember what the ID is from `igm view` then run the install so that it will install EarnApp again using the UUID set inside the config file. After the install is complete then register the device with the UUID from: `https://earnapp.com/r/<your_UUID_from_credential_file>` replacing the placeholder with the UUID. It should work, so you must be doing something wrong.

**Comment by thienha1** [comment]
yeah it work again but another problem is a Device always offline while it running

**Comment by XternA** [comment]
Would you mind showing me a screenshot of your dashboard's device section please?

One thing to note, don't always rely on the device status. Sometimes the device can show a 🔴 sign but if the `usage` tab is showing data then the device is actually online even without the 🟢 sign.

Since the device with that UUID is now correctly registered into your account. You can check the IGM config if the same UUID is used. Note that what's shown in the dashboard is a shorted version of your full UUID. As long as you see a matching with the UUID it's the same one. Try redeploy again.

Another option is, generate a new UUID and register as new, add the device to the dashboard and remove the old one.

Final option, try installing the application on a complete different device and see if it will stay online from the dashboard.

Also if you are using proxies, check that the proxy you're using works. There's lot of free proxies out there but it doesn't work at all.

**Comment by thienha1** [comment]
![Screenshot_20241210-2315462](https://github.com/user-attachments/assets/92805ee8-c958-42ce-9101-8dceff5fd526)
![Screenshot_20241210-2315512](https://github.com/user-attachments/assets/ab7a4c6f-8c5a-4f5a-a320-e9d341ab6a5b)
Here bro, tried several times, confirm not recognize at all

**Comment by XternA** [comment]
That's definitely confirmed not working then. The app is not restricted to any countries so your location should work. If you are running it with proxy then try another IP address. If it's your main ISP IP address then see if you can run it on a different IP address.

I won't be able to reproduce the issue but might just be your host. Perhaps try uninstalling Docker and installing it again and see if it helps. Another way you can debug is install the app manually, meaning go to the dashboard and download the binary for your platform. Run it that way and see if it will register and run the node. If it works that way then it might be best to uninstall everything, including `IGM` and start again.

My gut feeling based on all the reported issue by you seems to be related to your connection and DNS. If you're able to change the DNS from your router, it might be worth changing it to 1.1.1.1 or 8.8.8.8. These DNS should be able to resolve the destination.
