### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by robihut** [XternA/income-generator#65]
i have changed many different proxies even reinstalled new ubutu
the problem still appears
![screenshot_1733724690](https://github.com/user-attachments/assets/8417e994-bc13-4524-938b-e44fce2e6521)

**Comment by XternA** [comment]
Hi there,

The issue isn't to do with your Ubuntu instance. From the sounds of it you're using Windows.

First, remove all proxy app with `igm proxy remove`, then use `igm show` to see if there's still any proxy applications remaining. Secondly use `docker ps -a` to show everything unfiltered. 

If you see any instance of the proxy applications which will have a number appended at the end, remove it with `igm remove app_name` for instance `igm remove honeygain-2`

It's mostly because you have orphaned instances of the apps still lingering around. Before you go reinstalling the proxy applications again, run the following to cleanup `igm clean` this will remove any running orphans and images that's not used. Note that this will only remove containers that's already been stopped.

Now proceed with the proxy install again `igm proxy install`

**Comment by XternA** [comment]
@robihut - Please update your `IGM` tool to the latest version. I thought the issue was due to something else until I was hit with this problem recently. The following PR fixed the issue https://github.com/XternA/income-generator/pull/69. It was also related to permission issue. Latest update fixes the issue and confirmed working for me.
